name: Ironworker CI
on: [push, pull_request]
jobs:
  ci:
    name: "Test ${{ matrix.rust }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: "Install ${{matrix.rust}}"
        with:
            toolchain: ${{matrix.rust}}
            override: true
            components: clippy, rustfmt
      - uses: actions-rs/clippy-check@v1
        if: ${{matrix.rust == 'stable'}}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - uses: actions-rs/cargo@v1
        if: ${{matrix.rust == 'stable'}}
        with:
          command: fmt
          args: -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features